-- MySQL Script generated by MySQL Workbench
-- 01/12/17 11:09:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema G24
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `G24` ;

-- -----------------------------------------------------
-- Schema G24
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `G24` DEFAULT CHARACTER SET utf8 ;
USE `G24` ;

-- -----------------------------------------------------
-- Table `G24`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `G24`.`Usuario` (
  `Dni` VARCHAR(10) NOT NULL,
  `Usuario_Dni` VARCHAR(10) NULL,
  `rol` ENUM('administrador', 'entrenador', 'deportista') NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  PRIMARY KEY (`Dni`),
  INDEX `fk_Usuario_Usuario1_idx` (`Usuario_Dni` ASC),
  CONSTRAINT `fk_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_Dni`)
    REFERENCES `G24`.`Usuario` (`Dni`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `G24`.`Actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `G24`.`Actividad` (
  `idActividad` INT NOT NULL AUTO_INCREMENT,
  `Usuario_Dni` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `numPlazas` INT NOT NULL,
  `horario` DATETIME NOT NULL,
  `lugar` VARCHAR(45) NOT NULL,
  `tipoAct` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idActividad`),
  INDEX `fk_Actividad_Usuario1_idx` (`Usuario_Dni` ASC),
  CONSTRAINT `fk_Actividad_Usuario1`
    FOREIGN KEY (`Usuario_Dni`)
    REFERENCES `G24`.`Usuario` (`Dni`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `G24`.`Notificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `G24`.`Notificacion` (
  `idNotificacion` INT NOT NULL AUTO_INCREMENT,
  `Usuario_Dni` VARCHAR(10) NOT NULL,
  `Deportista_Usuario_Dni` VARCHAR(10) NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`idNotificacion`),
  INDEX `fk_Notificacion_Usuario1_idx` (`Usuario_Dni` ASC),
  CONSTRAINT `fk_Notificacion_Usuario1`
    FOREIGN KEY (`Usuario_Dni`)
    REFERENCES `G24`.`Usuario` (`Dni`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `G24`.`Entrenamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `G24`.`Entrenamiento` (
  `idEntrenamiento` INT NOT NULL AUTO_INCREMENT,
  `duracion` DOUBLE NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `completado` INT(1) NULL DEFAULT 0,
  `nivel` ENUM('principiante', 'intermedio', 'avanzado') NOT NULL,
  PRIMARY KEY (`idEntrenamiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `G24`.`Deportista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `G24`.`Deportista` (
  `DNI` VARCHAR(10) NOT NULL,
  `Usuario_Dni` VARCHAR(10) NOT NULL,
  `riesgos` VARCHAR(45) NOT NULL,
  `tipoDep` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DNI`),
  CONSTRAINT `fk_Deportista_Usuario1`
    FOREIGN KEY (`Usuario_Dni`)
    REFERENCES `G24`.`Usuario` (`Dni`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `G24`.`Reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `G24`.`Reserva` (
  `idReserva` INT NOT NULL AUTO_INCREMENT,
  `Deportista_Usuario_Dni` VARCHAR(10) NOT NULL,
  `Actividad_idActividad` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `plazas_ocupadas` INT(2) NOT NULL,
  PRIMARY KEY (`idReserva`),
  INDEX `fk_Reserva_Actividad1_idx` (`Actividad_idActividad` ASC),
  INDEX `fk_Reserva_Deportista1_idx` (`Deportista_Usuario_Dni` ASC),
  CONSTRAINT `fk_Reserva_Actividad1`
    FOREIGN KEY (`Actividad_idActividad`)
    REFERENCES `G24`.`Actividad` (`idActividad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Reserva_Deportista1`
    FOREIGN KEY (`Deportista_Usuario_Dni`)
    REFERENCES `G24`.`Deportista` (`DNI`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `G24`.`Ejercicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `G24`.`Ejercicio` (
  `idEjercicio` INT NOT NULL AUTO_INCREMENT,
  `Usuario_Dni` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `tipoEjer` VARCHAR(45) NOT NULL,
  `maquina` VARCHAR(45) NULL,
  `grupoMuscular` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(300) NULL,
  `imagen` VARCHAR(100) NULL,
  `video` VARCHAR(100) NULL,
  PRIMARY KEY (`idEjercicio`, `Usuario_Dni`),
  INDEX `fk_Ejercicio_Usuario1_idx` (`Usuario_Dni` ASC),
  CONSTRAINT `fk_Ejercicio_Usuario1`
    FOREIGN KEY (`Usuario_Dni`)
    REFERENCES `G24`.`Usuario` (`Dni`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `G24`.`Entrenamiento_has_Ejercicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `G24`.`Entrenamiento_has_Ejercicio` (
  `Entrenamiento_idEntrenamiento` INT NOT NULL,
  `Ejercicio_idEjercicio` INT NOT NULL,
  `series_repeticiones` VARCHAR(45) NOT NULL,
  `carga` FLOAT NULL,
  PRIMARY KEY (`Entrenamiento_idEntrenamiento`, `Ejercicio_idEjercicio`),
  INDEX `fk_Entrenamiento_has_Ejercicio_Ejercicio1_idx` (`Ejercicio_idEjercicio` ASC),
  INDEX `fk_Entrenamiento_has_Ejercicio_Entrenamiento1_idx` (`Entrenamiento_idEntrenamiento` ASC),
  CONSTRAINT `fk_Entrenamiento_has_Ejercicio_Entrenamiento1`
    FOREIGN KEY (`Entrenamiento_idEntrenamiento`)
    REFERENCES `G24`.`Entrenamiento` (`idEntrenamiento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Entrenamiento_has_Ejercicio_Ejercicio1`
    FOREIGN KEY (`Ejercicio_idEjercicio`)
    REFERENCES `G24`.`Ejercicio` (`idEjercicio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `G24`.`Sesion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `G24`.`Sesion` (
  `Deportista_Usuario_Dni` VARCHAR(10) NOT NULL,
  `Entrenamiento_has_Ejercicio_Entrenamiento_idEntrenamiento` INT NOT NULL,
  `Entrenamiento_has_Ejercicio_Ejercicio_idEjercicio` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `anotaciones` VARCHAR(100) NULL,
  PRIMARY KEY (`Deportista_Usuario_Dni`, `Entrenamiento_has_Ejercicio_Entrenamiento_idEntrenamiento`, `Entrenamiento_has_Ejercicio_Ejercicio_idEjercicio`, `fecha`),
  INDEX `fk_Sesion_Entrenamiento_has_Ejercicio1_idx` (`Entrenamiento_has_Ejercicio_Entrenamiento_idEntrenamiento` ASC, `Entrenamiento_has_Ejercicio_Ejercicio_idEjercicio` ASC),
  INDEX `fk_Sesion_Deportista1_idx` (`Deportista_Usuario_Dni` ASC),
  CONSTRAINT `fk_Sesion_Entrenamiento_has_Ejercicio1`
    FOREIGN KEY (`Entrenamiento_has_Ejercicio_Entrenamiento_idEntrenamiento` , `Entrenamiento_has_Ejercicio_Ejercicio_idEjercicio`)
    REFERENCES `G24`.`Entrenamiento_has_Ejercicio` (`Entrenamiento_idEntrenamiento` , `Ejercicio_idEjercicio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Sesion_Deportista1`
    FOREIGN KEY (`Deportista_Usuario_Dni`)
    REFERENCES `G24`.`Deportista` (`DNI`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `G24`.`Entrenamiento_has_Deportista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `G24`.`Entrenamiento_has_Deportista` (
  `Entrenamiento_idEntrenamiento` INT NOT NULL,
  `Deportista_DNI` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Entrenamiento_idEntrenamiento`, `Deportista_DNI`),
  INDEX `fk_Entrenamiento_has_Deportista_Deportista1_idx` (`Deportista_DNI` ASC),
  INDEX `fk_Entrenamiento_has_Deportista_Entrenamiento1_idx` (`Entrenamiento_idEntrenamiento` ASC),
  CONSTRAINT `fk_Entrenamiento_has_Deportista_Entrenamiento1`
    FOREIGN KEY (`Entrenamiento_idEntrenamiento`)
    REFERENCES `G24`.`Entrenamiento` (`idEntrenamiento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Entrenamiento_has_Deportista_Deportista1`
    FOREIGN KEY (`Deportista_DNI`)
    REFERENCES `G24`.`Deportista` (`DNI`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `G24`.`Notificacion_has_Deportista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `G24`.`Notificacion_has_Deportista` (
  `Notificacion_idNotificacion` INT NOT NULL,
  `Deportista_DNI` VARCHAR(10) NOT NULL,
  `Visto` INT(1) NULL DEFAULT 0,
  PRIMARY KEY (`Notificacion_idNotificacion`, `Deportista_DNI`),
  INDEX `fk_Notificacion_has_Deportista_Deportista1_idx` (`Deportista_DNI` ASC),
  INDEX `fk_Notificacion_has_Deportista_Notificacion1_idx` (`Notificacion_idNotificacion` ASC),
  CONSTRAINT `fk_Notificacion_has_Deportista_Notificacion1`
    FOREIGN KEY (`Notificacion_idNotificacion`)
    REFERENCES `G24`.`Notificacion` (`idNotificacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Notificacion_has_Deportista_Deportista1`
    FOREIGN KEY (`Deportista_DNI`)
    REFERENCES `G24`.`Deportista` (`DNI`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
